language: php

matrix:
    include:
        - os: linux
          dist: precise
          sudo: false
          php: 5.3
          env:
            - TEST_COVERAGE=true
        - os: linux
          dist: precise
          sudo: false
          php: 5.4
        - os: linux
          dist: precise
          sudo: false
          php: 5.5
        - os: linux
          dist: precise
          sudo: false
          php: 5.6
        - os: linux
          dist: trusty
          sudo: false
          php: 7
        - os: linux
          dist: trusty
          sudo: false
          php: 7.1
        - os: linux
          dist: trusty
          sudo: false
          php: hhvm
        - os: linux
          dist: trusty
          sudo: false
          php: nightly

before_script:
  - composer self-update
  - composer install
script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover ; else vendor/bin/phpunit ; fi
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TEST_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
